spring:
  application:
    name: security-commons
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}:8000/auth/realms/cinema-system

security:
  commons:
    oauth2:
      jwk-set-uri: http://${KEYCLOAK_HOST}:8000/auth/realms/cinema-system/protocol/openid-connect/certs
    cors:
      allowed-origins:
        - "*"
      allowed-headers:
        - "*"
      allowed-methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
